export { default as Services } from './Services';
export { default as Contact } from './Contact';
export { default as Review } from './Review';
export { default as Header } from './Header';
export { default as Footer } from './Footer';
export { default as Blogs } from './Blogs';
export { default as About } from './About';
export { default as Home } from './Home';
export { default as Menu } from './Menu';
